### PR TITLE
using switch - case instead of if else

### PR DESCRIPTION
**Pull request by chupper100**

### CODE REVIEW

**Comment by xhyrom** [comment]
Thanks 👍

**Comment by chupper100** [comment]
Does the new code work properly?

**Comment by xhyrom** [comment]
Ill check it, wait

**Comment by xhyrom** [comment]
Fixed - https://github.com/xHyroM/cf-workers-uploader/commit/bf04c11f8e0eccf71b117bd122b2c0dce60070e6  @chupper100

**Pull request merged**
